name: base
channels:
  - defaults
dependencies:
  - xarray=0.20.1
  - netcdf4=1.5.7
  - bottleneck=1.3.4
  - numpy=1.22.3
  - numpy-base=1.22.3
  - pandas=1.4.2
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.6
  - scikit-learn=1.0.2
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - keras=2.4.3
  - pyspark=3.1.2
  - mysql-connector-python
  - mysql-python
  - mysqlclient
  - pymysql=1.0.2
  - sqlalchemy=1.4.39
  - missingno=0.4.2
  - plotly=5.9.0
  - pip=22.2.2
  - beautifulsoup4=4.11.1
  # - psycopg2=2.9.5